name: spa
description: PotatoBeans SPA framework.
version: 1.1.1-alpha.1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  meta: any
  path: any
  test: any

dev_dependencies:
  pedantic: ^1.11.0
