name: spa
description: PotatoBeans SPA framework.
version: 1.6.3-alpha.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: any
  path: any
  test: any
  csslib: ^1.0.0
  collection: ^1.19.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
